y=input("What is your name?\n")
print("Hey there, " + y + "! That's a cool name!")
x=input("What is your favourite animal?\n")
print("Interesting choice! Animals are pretty cool.")
z=input("Pick a color\n")
print("That's a really cool color! I really like the color green.")
m=input("Do you have any hobbies?\n")
print("It's always good to do something to keep yourself busy.")
k=input("So " + y + ", did you like talking to a homebrew program?\n")
print("Thanks for your feedback! I loved talking to you, " + y + ". Hope to see you soon! Bye bye!")